#!/usr/bin/env ruby

# List out the 10 most recently committed branches.
# Wait for input and then attempt to checkout the branch you select by typing an index.

trap("INT") { exit }

exit unless system(`git rev-parse --is-inside-work-tree`)

branches = `git for-each-ref --sort=-committerdate refs/heads/ --format='%(refname:short)' | head`.chomp.split

exit unless branches.count > 0

puts branches.map.with_index { |branch, index| "[#{index}] #{branch}" }
puts
puts "[q] quit"

while branch = (branches[Integer(STDIN.gets)] rescue nil)
  exit if system "git checkout #{branch}"
  puts "Choose from the list above"
end
